### ISSUE TITLE
forgot to commit the patches you used

### ISSUE THREAD

**Issue by schraubenschluessel** [minikN/void-packages#1]
You forgot to commit the patches you used for the surface kernel, please do so so I can try building this

**Comment by minikN** [comment]
Updated. I've tried to build it myself yesterday, the build itself succeeded, but it failed at template:117:
`make ${makejobs} ARCH=${subarch:-$arch} INSTALL_MOD_PATH=${DESTDIR} modules_install` returning error code 2.

**Comment by minikN** [comment]
I'd like to fiddle around with it. But every build takes hours. Do you know where I can set the number of cores used?

**Comment by schraubenschluessel** [comment]
Do you have a logfile of that?

**Comment by minikN** [comment]
Where could I find one? I'm on #voidlinux btw.

**Comment by schraubenschluessel** [comment]
1 You can set the number of jobs to the number of CPU cores / threads by using `echo XBPS_MAKEJOBS=$(nproc) > etc/conf`
2 I prefer to use `nohup` which creates nohup.out as a default, but you could also use `tee` to create a logfile while running the build.

**Comment by minikN** [comment]
Thanks, I'll try it and report back.
(may take hours)

**Comment by minikN** [comment]
Do you know if it's possible to build the kernel using musl? I've setup xbps-src for musl, just wondering if that's also possible with the kernel in comparison to any other package.

**Comment by schraubenschluessel** [comment]
I don't think I would be a problem

**Comment by minikN** [comment]
any luck yet? Building with musl failed. Currently building using glibc.

**Comment by minikN** [comment]
Unfortunately it failed again.
Logs can be found [here](https://github.com/minikN/void-packages/tree/master/logs)

**Comment by minikN** [comment]
Btw, when starting to compile with glibc, these two question were asked:
- `GCC Plugins (GCC_PLUGINS) [N/y/?] (NEW)` - I answered `N`
- `Automatically load TTY Line Disciplines (LDISC_AUTOLOAD) [Y/n/?] (NEW)` -  I answered `Y`.

**Comment by schraubenschluessel** [comment]
https://www.kernel.org/doc/html/v4.15/admin-guide/module-signing.html

**Comment by minikN** [comment]
So it failed because `LibreSSL` only supports `SHA1` and not `SHA512` like set in the config?

**Comment by minikN** [comment]
Don't really know what the optimal solution would be. Change the algorithm to `SHA1` for all modules?

**Comment by schraubenschluessel** [comment]
AS I believe signed kernel modules are only required when using uefi secureboot, it should be possible to disable it altogether if you are not using secure boot

**Comment by minikN** [comment]
Hm, alright. Have you tried to build it yet?

**Comment by schraubenschluessel** [comment]
I was able to build the package, but it did not apply the patches before building, still looking into this

**Comment by minikN** [comment]
How much disk space did you need during build? thr last two attempts failed because I ran out of it. Last try was with 20 GB.

**Comment by minikN** [comment]
Eventually I was able to build it as well. However after installing it, nothing changed. Still no touch or anything else.

**Comment by schraubenschluessel** [comment]
I was able to build a package with the module inside, using a kernel config without module signing.
Were you able to load the intel-ipts module via `modprobe intel-ipts` when installing the kernel package without module signing?

**Comment by schraubenschluessel** [comment]
https://github.com/the-wrench99/void-packages/tree/surface-kernel have fun :)

**Comment by minikN** [comment]
I was also able to build the kernel. I just took the default void config file and added

```
# Surface related kernel configs
CONFIG_INTEL_IPTS=m
CONFIG_MEDIA_CEC_RC=y
# CONFIG_MWLWIFI is not set
CONFIG_NET_DSA_MV88E6060=m
CONFIG_NET_DSA_TAG_TRAILER=y
CONFIG_OVERLAY_FS_NFS_EXPORT=n
CONFIG_SURFACE_3_POWER_OPREGION=m
CONFIG_SURFACE_ACPI=m
CONFIG_SURFACE_ACPI_SAN=y
CONFIG_SURFACE_ACPI_SSH=y
CONFIG_SURFACE_ACPI_SSH_DEBUG_DEVICE=n
CONFIG_SURFACE_ACPI_VHF=y
CONFIG_SURFACE_ACPI_DTX=y
CONFIG_SURFACE_ACPI_SID=y
```

Now the output of `lsmod | grep ipts`

```
intel_ipts             28672  0
mei                    94208  3 intel_ipts,mei_me
hid                   131072  7 usbhid,hid_multitouch,hid_sensor_hub,intel_ipts,intel_ishtp_hid,hid_generic,uhid
i915                 2097152  10 intel_ipts
```

`lsmod | grep surface`
`surfacepro3_button     16384  0`

`zgrep /proc/config.gz`
```
CONFIG_TOUCHSCREEN_SURFACE3_SPI=m
CONFIG_SURFACE3_WMI=m
CONFIG_SURFACE_ACPI=m
CONFIG_SURFACE_PRO3_BUTTON=m
CONFIG_SURFACE_3_POWER_OPREGION=m
```

Does that mean the modules got loaded properly? If so, I still see no difference. Nothing is working (or I'm testing it the wrong way).

If I do `cat /dev/input/event*` and touch my screen, nothing happens.

Regarding signing modules, there is also [this](https://github.com/jakeday/linux-surface/blob/master/SIGNING.md) page. Don't know if it's of any use?

**Comment by schraubenschluessel** [comment]
I believe that the issue with the kernel driver is resolved now and this is an issue with an user space program

**Comment by minikN** [comment]
Let me tell you this is starting to become exhausting. I'm building with your config now, maybe that will have a difference.

**Comment by minikN** [comment]
Another question is, let's say I get this to work and then they update the kernel version on the `void-packages` repo, will I then have to rebuild it?

**Comment by schraubenschluessel** [comment]
Probably yes

**Comment by minikN** [comment]
Okay, finally something good: Using your config touch is working!

**Comment by minikN** [comment]
Thank you for your work so far. Next step would be to get the power / volume buttons to work properly.

**Comment by schraubenschluessel** [comment]
you could try if the volume buttons show up in `xev` when being pressed

**Comment by minikN** [comment]
Unfortunately they don't.

**Comment by minikN** [comment]
I was able to fix the button issue. All of thrm are working now. The only thing left that is not working is suspend or rather wake up. Suspending the device sort of soft locks it. When suspended, no buttons what so ever have any effect. I need to hard reset the device by holding the power button for 15 seconds.

**Comment by schraubenschluessel** [comment]
https://github.com/jimdigriz/debian-mssp4/blob/master/root/lib/systemd/system-sleep/cover-wakeup.sh
could that be of help?

**Comment by minikN** [comment]
Hm, I dont know. How would I implement it?

**Comment by minikN** [comment]
Oh, I see how. I just have to execute it in the right event in acpi's handler.sh?

**Comment by minikN** [comment]
There is also [this](https://github.com/jakeday/linux-surface/blob/master/root/lib/systemd/system-sleep/sleep) script. Which may fix my issue. However I don't know how to implement it since it's for systemd. For `acpid`, there is only one event for power button pressed: `button/power PBTN 00000080 00000000`. 

I don't know how to implement the `pre` and `post` arguments in the script since the event is the same for both in `/etc/acpi/handler.sh`.

**Comment by minikN** [comment]
Okay little update: I copied the `pre` section from the sleep script to `/etc/zzz.d/suspend/sleep` and the `post` section to `/etc/zzz.d/resume/resume`. Now suspending is working properly, also waking up is working, however, it suspends immediately after it wakes up. Seems like I'm facing the issue in the script you provided.

**Comment by minikN** [comment]
My idea was to set env vars accordinflg to the state (just woken up or ready to suspend). 

However I cant access env var from within handler.sh. Dont know why really.

**Comment by schraubenschluessel** [comment]
Maybe you have to disable additional suspend events, you should try to log the acpi events after wake up

**Comment by minikN** [comment]
How would I disable them? Were are the events being logged?

**Comment by schraubenschluessel** [comment]
Events can be disabled through the sysfs, I think acpi events can be logged trough the acpid and syslog, but you need a syslogd (rsyslog or metalog) running for that.
Acpid documentation: https://linux.die.net/man/8/acpid

**Comment by minikN** [comment]
Hm, doesn't seem to get my anywhere, I started rsyslogd. `acpid`'s logging flag `-l` is set by default. Still no log file in `/var/log`.

**Comment by schraubenschluessel** [comment]
What files are in /var/log?

**Comment by minikN** [comment]
```
Xorg.0.log
Xorg.0.log.old
Xorg.1.log
Xorg.1.log.old
btmp
dmesg.log
faillog
lastlog
messages
secure
tallylog
wtmp
```

**Comment by minikN** [comment]
```
sudo sv status rsyslogd
run: rsyslogd: (pid 855) 124s
```

**Comment by schraubenschluessel** [comment]
Try `/var/log/messages`

**Comment by minikN** [comment]
[log](https://github.com/minikN/void-packages/blob/master/logs/messages)

**Comment by schraubenschluessel** [comment]
`acpid` seems to habe a debug flag (`-d`) maybe you can use that together with runit's logging capability.
Sadly I do not have any experience with acpid.

**Comment by minikN** [comment]
Will try that. In the meantime, here is the output of `find /sys -name wakeup -printf '%p ' -exec cat {} \;`: [link](https://github.com/minikN/void-packages/blob/master/logs/wakeup_events)

Also, doing

```
modprobe -r intel_ipts
modprobe -r mei_me
modprobe -r mei
rtcwake -m freeze -s 10
```

works as expected. The surface suspends for 10 secs and comes back without a problem.

**Comment by schraubenschluessel** [comment]
Maybe try unloading the modules in the `/etc/zzz.d/suspend/sleep` script and loading them in the `/etc/zzz.d/resume/resume` script?

**Comment by minikN** [comment]
I already did that. I took [that](https://github.com/jakeday/linux-surface/blob/master/root/lib/systemd/system-sleep/sleep) script and added the `pre` case to `/etc/zzz.d/suspend/sleep` and the `post` case to `/etc/zzz.d/resume/resume`.

(Of course I adjusted the `NetworkManager` line to work with `sv`.

Before I did that, suspend wasn't working at all (it was softlocking immediately).
After that, I got to the point where suspending worked, but waking up ended up in the loop I'm facing now.

**Comment by schraubenschluessel** [comment]
Any updates?
I was not able to find any further information

**Comment by minikN** [comment]
Sadly no. I just deactvated sleep all together.

**Comment by schraubenschluessel** [comment]
Would you mind documenting the steps you took for the void-docs?
https://github.com/void-linux/void-docs/blob/master/src/installation/guides/index.md

I think the kernel config should be named x86_64-dotconfig-custom

**Comment by minikN** [comment]
Sure. Where exactly should I put the documentation?

**Comment by schraubenschluessel** [comment]
In the [void-docs](https://github.com/void-linux/void-docs) repository under `src/installation/guides/` [directory](https://github.com/void-linux/void-docs/blob/master/src/installation/guides/) I think.

It should probably cover:
* the exact hardware you used
* what does work, what does not
* the base installation
* the custom kernel build
* the configuration you changed

**Comment by minikN** [comment]
I'm sorry I'm being stupid here. Do you want me to do a PR? The fact that there are no other guides in that directory makes me think I'm misunderstanding it completely.

**Comment by schraubenschluessel** [comment]
In the readme, it states that the guidelines for contributing are the same as with void-packages: https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md

**Comment by minikN** [comment]
Hey, sorry to bother you again about this. But I had to reinstall my system (I wanted to switch from `musl` to `glibc`. I noticed that there is no `linux5.0` package anymore in the `void-packages` repo. Also jakeday updated this version to `5.1` as well. I tried compiling the kernel with his `5.1` config and disabling module signing. However I failed again. No touch.

Can you tell me how you build your `5.0` config that worked? What file did you use as a template, the one from jakeday or the void-packages one? Also what flags exactly did you change?

I want to be able to do this on my own, not ask you anytime I need to do this.

Thanks.
